source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NubiumMessaging-iOS_Example', :exclusive => true do
  pod 'NubiumMessaging-iOS', :path => '../'
end

target 'NubiumMessaging-iOS_Tests', :exclusive => true do
  pod 'NubiumMessaging-iOS', :path => '../'

  
end
